---
title: "Analysis"
output: html_document
---

```{r}
library(tidyverse)
library(readr)
collegescorecard <- read_csv("group-h-csv.csv", na = c("", "NA", "NULL", "PrivacySuppressed"),
    col_types = cols(ADM_RATE = col_number(), 
        ADM_RATE_ALL = col_number(), C150_4 = col_number(), 
        COMPL_RPY_3YR_RT_SUPP = col_number(), 
        CONTROL = col_character(), COSTT4_A = col_number(), 
        DEP_RPY_3YR_RT_SUPP = col_number(), 
        FAMINC = col_number(), FEMALE_RPY_3YR_RT_SUPP = col_number(), 
        FIRSTGEN_RPY_3YR_RT_SUPP = col_number(), 
        GRAD_DEBT_MDN10YR_SUPP = col_number(), 
        GRAD_DEBT_MDN_SUPP = col_number(), 
        HIGHDEG = col_character(), HI_INC_RPY_3YR_RT_SUPP = col_number(), 
        ICLEVEL = col_character(), IND_RPY_3YR_RT_SUPP = col_number(), 
        LO_INC_RPY_3YR_RT_SUPP = col_number(), 
        MALE_RPY_3YR_RT_SUPP = col_number(), 
        MD_EARN_WNE_P10 = col_number(), MD_FAMINC = col_number(), 
        MD_INC_RPY_3YR_RT_SUPP = col_number(), 
        MN_EARN_WNE_P10 = col_number(), NONCOM_RPY_3YR_RT_SUPP = col_number(), 
        NOPELL_RPY_3YR_RT_SUPP = col_number(), 
        NOTFIRSTGEN_RPY_3YR_RT_SUPP = col_number(), 
        NPT4_PRIV = col_number(), NPT4_PUB = col_number(), 
        OPEID = col_character(), PCTFLOAN = col_number(), 
        PCTPELL = col_number(), PELL_RPY_3YR_RT_SUPP = col_number(), 
        PFTFAC = col_number(), PREDDEG = col_character(), 
        RPY_3YR_RT_SUPP = col_number(), SAT_AVG = col_number(), 
        TUITFTE = col_number(), TUITIONFEE_IN = col_number(), 
        TUITIONFEE_OUT = col_number(), UNITID = col_character()))

collegescorecard<- collegescorecard%>% mutate(SCH_DEG=as.factor(SCH_DEG), PREDDEG=as.factor(PREDDEG), HIGHDEG=as.factor(HIGHDEG), CONTROL=as.factor(CONTROL)) 

```

## Explanatory Variables: 

Mean family income: quantitative Unit: dollars
Using data from NSLDS, these elements calculate the percentage of Title IV-receiving students who had family income data from the Free Application for Federal Student Aid (FAFSA) for each of five income quintiles.

Tuition cost: quantitative Unit: dollars
Includes tuition and fees, books, and supplies, and living expenses for all full-time, first-time, degree/certificate-seeking undergraduates who receive Title IV aid.

Percent of students on Pell grants: quantitative Unit: percent
Calculated from values from the IPEDS Student Financial Aid Component.

Percent of students receiving federal loan: quantitative Unit: percent
Calculated from values from the IPEDS Student Financial Aid Component

Cumulative mean debt: quantitative Unit: dollars 
Represents the sum of all undergraduate federal loans over students’ college education at the institution for which the median debt is reported for —e.g., if a student receives a federal loan for $2,000 for each of eight semesters at one institution, their cumulative debt is recorded as 
$16,000 for that institution. 

School Type: categorical Categories: private, public, trade

